name: Lint and compile
on:
  push:
    paths:
      - 'workspace/**'

jobs:
  lint:
    name: ament_flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros2-lint@master
        with:
          linter: flake8
          package-name: workspace
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - name: build
        run: |
          cd workspace && colcon build