name: CI
on:
  push:
    paths:
      - "workspace/launch/**"
      - "workspace/src/**"
      - "workspace/lint.sh"
      - "workspace/pytest.ini"
      - "workspace/.coveragerc"
      - "codecov.yml"
      - ".github/workflows/main.yml"

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - name: Install dependencies
        run: |
          sudo apt install libzbar-dev pycodestyle python3-opencv ros-foxy-ros-base -y
          pip3 install -U pytest
          pip3 install pyzbar pytest-env
          rosdep update
          cd workspace && rosdep install -i --from-path src --rosdistro foxy -y
      - name: Build
        run: |
          cd workspace && colcon build --symlink-install
      - name: Lint
        run: |
          cd workspace && ./lint.sh
      - name: Run tests and generage code coverage report
        run: |
          cd workspace && source /opt/ros/foxy/setup.bash && DELAY=1 coverage run --branch -m pytest src && coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./workspace/coverage.xml
