name: CI
on:
  push:
    paths:
      - "workspace/launch/**"
      - "workspace/src/**"
      - "workspace/lint.sh"
      - "workspace/pytest.ini"
      - ".github/workflows/main.yml"

jobs:
  build-lint-and-run-tests:
    name: Build, lint, and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - name: Install dependencies
        run: |
          sudo apt install libzbar-dev pycodestyle python3-opencv ros-foxy-ros-base -y
          pip3 install -U pytest
          pip3 install pyzbar pytest-env
          rosdep update
          cd workspace && rosdep install -i --from-path src --rosdistro foxy -y
      - name: Build
        run: |
          cd workspace && colcon build --symlink-install
      - name: Lint
        run: |
          cd workspace && ./lint.sh
      - name: Run tests
        run: |
          cd workspace && source /opt/ros/foxy/setup.bash && pytest src
