name: CI
on:
  push:
    paths:
      - "workspace/**"

jobs:
  build-and-lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - name: Install pycodestyle
        run: |
          sudo apt install pycodestyle
      - name: Build and lint
        run: |
          cd workspace && colcon build && ./lint.sh
